-- ----------------------------
-- Table structure for fb
-- ----------------------------
DROP TABLE IF EXISTS "public"."fb";
CREATE TABLE "public"."fb" (
  "_rid" text NOT NULL PRIMARY KEY,
  "post_id" text ,
  "post_time" timestamptz(6),
  "source" text ,
  "data_category" text,
  "page_category" text,
  "post_status" text,
  "post_identity" text,
  "from_id" text,
  "from_name" text,
  "page_id" text,
  "page_name" text,
  "body"text,
  "title"text,
  "caption"text,
  "description"text,
  "hashtag"jsonb,
  "url"text,
  "related_link" text,
  "image_links" jsonb,
  "image_alts" jsonb,
  "attachment_type" text,
  "attachment_url" text,
  "post_tags" jsonb,
  "comments" jsonb,
  "image_md5" text,
  "cs" numeric,
  "cc" numeric,
  "cl" numeric,
  "ca" numeric,
  "cd" numeric,
  "ch" numeric,
  "co" numeric,
  "cw" numeric,
  "ct" numeric,
  "cu" numeric,
  "cp" numeric,
  "interval" numeric,
  "diff" numeric,
  "diff_comment" numeric,
  "diff_share" numeric,
  "track_time" timestamptz(6)
)
;